export const AppContent = {
  login: "Login",
  register: "Register",
  ok: "OK",
  cancel: "Cancel",
  save: "Save",
  delete: "Delete",
  edit: "Edit",
  update: "Update",
  add: "Add",
  search: "Search",
  reset: "Reset",
  close: "Close",
  clear: "Clear",
  confirm: "Confirm",
  submit: "Submit",
  success: "Success",
  error: "Error",
  warning: "Warning",
  info: "Info",
  required: "Required",
  invalid: "Invalid",
};
